version: "3.2"

services:
  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

      MYSQL_ROOT_HOST: "%"


    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
