version: "3.2"

<<<<<<< HEAD

services:
  database:
    restart: always
    image: mysql/mysql-server:latest
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root


volumes:
  mysql-datavolume:
    driver: local
=======
services:
  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

      MYSQL_ROOT_HOST: "%"


    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
>>>>>>> separate
